import { pgTable, uuid, text, date, timestamp, jsonb, index } from 'drizzle-orm/pg-core';
import { genderTypeEnum, verticalTypeEnum, studentStatusEnum, renewalStatusEnum } from './enums';
import { users } from './users';

export const students = pgTable('students', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').notNull().unique().references(() => users.id, { onDelete: 'cascade' }),
  gender: genderTypeEnum('gender'),
  dateOfBirth: date('date_of_birth'),
  aadharNumber: text('aadhar_number'),
  nativePlace: text('native_place'),
  permanentAddress: text('permanent_address'),
  fatherName: text('father_name'),
  fatherMobile: text('father_mobile'),
  motherName: text('mother_name'),
  motherMobile: text('mother_mobile'),
  guardianName: text('guardian_name'),
  guardianMobile: text('guardian_mobile'),
  guardianRelation: text('guardian_relation'),
  institution: text('institution'),
  course: text('course'),
  yearOfStudy: text('year_of_study'),
  enrollmentNumber: text('enrollment_number'),
  vertical: verticalTypeEnum('vertical').notNull(),
  joiningDate: date('joining_date'),
  currentPeriod: text('current_period'),
  academicYear: text('academic_year'),
  status: studentStatusEnum('status').notNull().default('PENDING'),
  renewalStatus: renewalStatusEnum('renewal_status').default('NOT_DUE'),
  renewalDueDate: date('renewal_due_date'),
  lastRenewalDate: date('last_renewal_date'),
  emergencyContactName: text('emergency_contact_name'),
  emergencyContactPhone: text('emergency_contact_phone'),
  emergencyContactRelation: text('emergency_contact_relation'),
  bloodGroup: text('blood_group'),
  medicalConditions: text('medical_conditions'),
  allergies: text('allergies'),
  metadata: jsonb('metadata').default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  index('idx_students_vertical').on(table.vertical),
  index('idx_students_status').on(table.status),
  index('idx_students_renewal_status').on(table.renewalStatus),
  index('idx_students_father_mobile').on(table.fatherMobile),
  index('idx_students_mother_mobile').on(table.motherMobile),
]);
