import { db } from '@/lib/db';
import { applications } from '@/lib/db/schema';
import { eq, and, desc, sql, count, SQL } from 'drizzle-orm';
import { NotFoundError, ForbiddenError } from '@/lib/errors';

type AppInsert = typeof applications.$inferInsert;
type UserRole = 'STUDENT' | 'SUPERINTENDENT' | 'TRUSTEE' | 'ACCOUNTS' | 'PARENT';

export async function createApplication(data: Omit<AppInsert, 'id' | 'trackingNumber' | 'createdAt' | 'updatedAt'>) {
  // Tracking number is auto-generated by DB trigger
  const [app] = await db.insert(applications).values({
    ...data,
    trackingNumber: '', // trigger will override
    currentStatus: 'DRAFT',
  }).returning();
  return app;
}

export async function getApplicationById(id: string) {
  const [app] = await db.select().from(applications).where(eq(applications.id, id));
  if (!app) throw new NotFoundError('Application not found');
  return app;
}

export async function getApplicationByTracking(trackingNumber: string, mobile: string) {
  const [app] = await db.select().from(applications)
    .where(and(
      eq(applications.trackingNumber, trackingNumber),
      eq(applications.applicantMobile, mobile),
    ));
  if (!app) throw new NotFoundError('Application not found');
  return app;
}

export async function updateApplication(
  id: string,
  updates: Partial<AppInsert>,
  userRole: UserRole,
) {
  const app = await getApplicationById(id);

  if (userRole === 'STUDENT' && !['DRAFT', 'SUBMITTED'].includes(app.currentStatus)) {
    throw new ForbiddenError('Students can only update DRAFT or SUBMITTED applications');
  }

  const [updated] = await db.update(applications)
    .set(updates)
    .where(eq(applications.id, id))
    .returning();
  return updated;
}

export async function updateApplicationStatus(
  id: string,
  status: string,
  userId: string,
  reason?: string,
) {
  const updates: Partial<AppInsert> = { currentStatus: status as AppInsert['currentStatus'] };

  if (status === 'APPROVED') {
    updates.approvedAt = new Date();
    updates.approvedBy = userId;
  } else if (status === 'REJECTED') {
    updates.rejectedAt = new Date();
    updates.rejectedBy = userId;
    updates.rejectionReason = reason;
  } else if (status === 'SUBMITTED') {
    updates.submittedAt = new Date();
  } else if (status === 'REVIEW') {
    updates.reviewedAt = new Date();
  }

  const [updated] = await db.update(applications)
    .set(updates)
    .where(eq(applications.id, id))
    .returning();
  if (!updated) throw new NotFoundError('Application not found');
  return updated;
}

export async function listApplications(filters: {
  userId?: string;
  userRole: UserRole;
  userVertical?: string | null;
  status?: string;
  type?: string;
  page?: number;
  limit?: number;
}) {
  const { page = 1, limit = 20 } = filters;
  const offset = (page - 1) * limit;

  const conditions: SQL[] = [];

  if (filters.userRole === 'STUDENT' && filters.userId) {
    conditions.push(eq(applications.studentUserId, filters.userId));
  } else if (filters.userRole === 'SUPERINTENDENT' && filters.userVertical) {
    conditions.push(sql`${applications.vertical} = ${filters.userVertical}`);
  }

  if (filters.status) {
    conditions.push(sql`${applications.currentStatus} = ${filters.status}`);
  }
  if (filters.type) {
    conditions.push(sql`${applications.type} = ${filters.type}`);
  }

  const where = conditions.length > 0 ? and(...conditions) : undefined;

  const [data, [{ total }]] = await Promise.all([
    db.select().from(applications).where(where).orderBy(desc(applications.createdAt)).limit(limit).offset(offset),
    db.select({ total: count() }).from(applications).where(where),
  ]);

  return { data, total, page, limit };
}

export async function getApplicationStats(userRole: UserRole, userVertical?: string | null) {
  const conditions: SQL[] = [];
  if (userRole === 'SUPERINTENDENT' && userVertical) {
    conditions.push(sql`${applications.vertical} = ${userVertical}`);
  }

  const where = conditions.length > 0 ? and(...conditions) : undefined;

  const result = await db.select({
    status: applications.currentStatus,
    count: count(),
  }).from(applications).where(where).groupBy(applications.currentStatus);

  return Object.fromEntries(result.map((r) => [r.status, r.count]));
}
